apiVersion: apps/v1
kind: Deployment
metadata:
  name: readylive
  labels:
    app: readylive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readylive
  template:
    metadata:
      labels:
        app: readylive
    spec:
      containers:
        - name: readylive
          image: readylive:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /id
              port: 8080
            failureThreshold: 1
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /id
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 8
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: readylive
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: readylive
  type: LoadBalancer
